### ISSUE TITLE
Android Crashes to home screen when launching Spore

### ISSUE THREAD

**Issue by LimitTheorem** [hikari-no-yume/touchHLE#439]
### App DB report link

https://appdb.touchhle.org/apps/302#version-788

### App name

Spore

### App version

1.0

### touchHLE version

v0.2.2

### Operating system

Android 14 (CalyxOS 5.17.1)

### GPU

Adreno 618

### What is the problem with the app?

Hardware:
Phone: Pixel 4a
Chipset: Qualcomm SDM730 Snapdragon 730G
RAM: 6GB

I tried the "Touch and Go" app available on your web page and confirmed that at least does run, but Spore doesn't and produces some invalid memory operation. I tired this on the previous version of touchHLE and it didn't work either, but I gave up and didn't bother to submit a report at that time. When I saw you made a new release, I figured I would try again but it still fails.

### If touchHLE crashed, please paste the log output.

```text
touchHLE v0.2.2 — https://touchhle.org/

touchHLE: Base path for touchHLE files: /storage/emulated/0/Android/data/org.touchhle.android/files
No app specified, opening app picker. Use the --help flag to see command-line usage.
touchHLE::app_picker: Warning: couldn't open app bundle /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/SMB Lite.ipa: Could not open IPA archive: invalid Zip archive: Could not find central directory end (skipping)
touchHLE::app_picker: Warning: couldn't open app bundle /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/Toy Bot Free 1.ipa: Could not open IPA archive: invalid Zip archive: Could not find central directory end (skipping)
touchHLE::window: Accelerometer detected: LSM6DSR Accelerometer.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 618
Picked: /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_apps/Spore.ipa
App bundle info:
- Display name: Spore
- Version: 1.0
- Identifier: com.ea.spore.row.efigsj
- Internal name (canonical): Spore.app
- Minimum OS version: (not specified)

No options found for this app in touchHLE_default_options.txt
No options found for this app in /storage/emulated/0/Android/data/org.touchhle.android/files/touchHLE_options.txt

touchHLE::window: Accelerometer detected: LSM6DSR Accelerometer.
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::window: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 618
touchHLE::mach_o: Loading armv6 slice for "Spore"
touchHLE::mach_o: Loading armv6 slice for "libstdc++.6.dylib"
touchHLE::mach_o: Loading armv6 slice for "libgcc_s.1.dylib"
touchHLE::dyld: Warning: unhandled non-lazy symbol "___mb_cur_max" at 0x3f48a654 in "libstdc++.6.dylib"
CPU emulation begins now.
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef884), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x374ef8b8), 0x0, 0x3748a000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2090), 0xfffffea8, 0xfffffea8) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffea8) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_finalize(0xfffffea8) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7460, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7470, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7480, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7490, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f74f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7500, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7510, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7520, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7530, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7540, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7550, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7560, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7570, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7580, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7590, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f75f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7600, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7610, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7620, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7630, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7640, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7650, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7660, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7670, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7680, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7690, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f76f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7700, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7710, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7720, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7730, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7740, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7750, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7760, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7770, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7780, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7790, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f77f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7800, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7810, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7820, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7830, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7840, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7850, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7860, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7870, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7880, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7890, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f78f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7900, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7910, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7920, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7930, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7940, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7950, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7960, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7970, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7980, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7990, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79a0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79b0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79c0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79d0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79e0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f79f0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a00, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a10, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a20, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a30, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a40, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a50, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a60, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a70, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a80, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7a90, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7aa0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ab0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ac0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ad0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ae0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7af0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b00, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b10, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b20, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b30, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b40, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b50, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b60, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b70, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b80, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7b90, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ba0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7bb0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7bc0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7bd0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7be0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7bf0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c00, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c10, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c20, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c30, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c40, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c50, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c60, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c70, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c80, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7c90, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ca0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7cb0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7cc0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7cd0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7ce0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7cf0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d00, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d10, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d20, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d30, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d40, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d50, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d60, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d70, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d80, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7d90, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7da0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7db0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7dc0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7dd0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7de0, 0x1000) (unimplemented)
touchHLE::libc::cxxabi: TODO: __cxa_atexit(GuestFunction(0x2544), 0x374f7df0, 0x1000) (unimplemented)
touchHLE::gles: Creating an OpenGL ES 1.1 context:
touchHLE::gles: Trying: Native OpenGL ES 1.1
touchHLE::gles: => Success!
touchHLE::frameworks::opengles::eagl: Driver info: OpenGL ES-CM 1.1 / Qualcomm / Adreno (TM) 618
touchHLE::frameworks::foundation::ns_locale: The app requested your preferred languages. ["en"] will be reported based on your system language preferences.
touchHLE::frameworks::openal: alGetError() called with no current context. Ignoring and returning AL_NO_ERROR for compatibility with Super Monkey Ball.
touchHLE::frameworks::openal: App wants to set mixer output sample rate to 22050 Hz
touchHLE::frameworks::openal: alGetError() called with no current context. Ignoring and returning AL_NO_ERROR for compatibility with Super Monkey Ball.
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x375091c0 initWithContentURL:0x375091d0 (GuestPathBuf("/var/mobile/Applications/00000000-0000-0000-0000-000000000000/Spore.app/Data/Movies/Intro.mov"))]
touchHLE::frameworks::media_player::movie_player: Applying game-specific hack for Spore Origins: sending MPMoviePlayerPlaybackDidFinishNotification again.
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x375091c0 play]
touchHLE::frameworks::media_player::movie_player: Applying game-specific hack for Spore Origins: sending MPMoviePlayerPlaybackDidFinishNotification again.
touchHLE::window: This app uses the accelerometer.
touchHLE::window: Your device's accelerometer will be used for accelerometer simulation.
touchHLE::window: Connect a controller if you would prefer to use an analog stick.
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x375091c0 stop]
touchHLE::frameworks::media_player::movie_player: TODO: [(MPMoviePlayerController*)0x375091c0 play]
touchHLE::frameworks::openal: alGetError() called with no current context. Ignoring and returning AL_NO_ERROR for compatibility with Super Monkey Ball.
touchHLE::frameworks::openal: App wants to set mixer output sample rate to 22050 Hz
touchHLE::frameworks::openal: alGetError() called with no current context. Ignoring and returning AL_NO_ERROR for compatibility with Super Monkey Ball.
Panic at src/mem.rs:337:9: Attempted null-page access at 0x0 (0x4 bytes)
Panic at src/environment.rs:739:13: Error during CPU execution: MemoryError
Register state immediately after panic:
	 R0: 0x00000000	 R1: 0x00000000	 R2: 0x00000000	 R3: 0x000b12cc
	 R4: 0x000b12c8	 R5: 0x001c73a0	 R6: 0x375092e0	 R7: 0xffffff20
	 R8: 0x000b12c8	 R9: 0x0000ffff	R10: 0x00000000	R11: 0x00000000
	R12: 0x000b1ca4	 SP: 0xffffff0c	 LR: 0x0006d23f	 PC: 0x00000004
Attempting to produce stack trace for main thread:
 0. 0x4 (PC)
 1. 0x6d23f (LR)
 2. [host function]
 3. 0x2034
Next FP (0x0) is outside the stack.
```

### By submitting this issue, I certify that…

- [x] I have tested that this version of this app is at least partially working in a previous version of touchHLE.
- [x] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [x] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment]
There is no appdb report claiming that version 1.0.0 of Spore works in version 0.2.2 of touchHLE. As such this is not a valid regression report.

You may want to try one of the preview builds of touchHLE: https://touchhle.org/download/

**Comment by LimitTheorem** [comment]
Okay I see. I didn't realize the entries in the table that were hyphenated with a hash in the version string were dev/preview release builds, sorry.
